### ISSUE TITLE
Ne readme Datei wäre gut

### ISSUE THREAD

**Issue by TheGreyDiamond** [fleaz/elendsindex#1]
Eine Readme.md wäre ganz schön.

**Comment by TheGreyDiamond** [comment]
Also ein nein

**Comment by fleaz** [comment]
@TheGreyDiamond Hä? Ich hab dein Issue doch vorgestern nach gerademal 30 Minuten gefixt und ne README ins Repo gepackt?

**Comment by TheGreyDiamond** [comment]
Achso, hatte nicht geguckt. Hatte nur gesehn das das Issue zu gemacht wurde. SOrry
